# Generated by Django 6.0.3 on 2026-05-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_alter_categoria_porcentajeganancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='IdProveedor',
            field=models.ForeignKey(blank=True, db_column='IdProveedor', null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogo.proveedor'),
        ),
        migrations.AddField(
            model_name='producto',
            name='Presentacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
