# Generated by Django 6.0.4 on 2026-05-20 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_merge_20260423_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleentradainventario',
            name='TipoCompra',
            field=models.CharField(default='unidad', max_length=30),
        ),
    ]
