# Generated by Django 6.0.3 on 2026-06-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_detalleentradainventario_tipocompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleentradainventario',
            name='TipoCompra',
            field=models.CharField(blank=True, default='unidad', max_length=30, null=True),
        ),
    ]
