# Generated by Django 6.0.3 on 2026-06-01 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_groups_usuario_user_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, default=None, help_text='Timestamp UTC hasta el cual se bloquea el login. None = sin bloqueo activo.', null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='intentos_fallidos',
            field=models.IntegerField(default=0, help_text='Contador de contraseñas incorrectas consecutivas. Se resetea en login exitoso.'),
        ),
    ]
